### ISSUE TITLE
Dynamic import replaced by webpack

### ISSUE THREAD

**Issue by unlight** [colscott/a-wc-router#1]
In your code there is an `import` statement.
Webpak converts it to
```
__webpack_require__("./node_modules/a-wc-router/src lazy recursive")(importSrc);
```
Which lead to error:
```
Cannot find module
```

While compiling it gives warning:
```
WARNING in ./node_modules/a-wc-router/build/es6-bundled/src/router.js 58:117-134
Critical dependency: the request of a dependency is an expression
```

Do you know how it can be fixed?

**Comment by colscott** [comment]
Hi @unlight, looks like Webpack doesn't support dynamic imports unless the import is a known module at compile time.
I found a few posts with similar issues:
https://github.com/webpack/webpack/issues/8341
https://github.com/webpack/webpack/issues/6680

Could you try editing /node_modules/a-wc-router/build/es6-bundled/src/router.js prior to running webpack?
Try changing:
`import(importSrc)`
To:
`import(/* webpackIgnore: true */importSrc)`

If this works I'll create a patch version that has that change in it.

**Comment by colscott** [comment]
@unlight I pushed a new version 1.1.1. It has the change to the source code but not the build.
`await import(/* webpackIgnore: true */importSrc);`

Since you're using webpack anyway, try importing ./node_modules/a-wc-router/src/router.js instead of the build version. This will have the webpackIgnore comment.

**Comment by unlight** [comment]
@colscott 
Thank you very much. Yes, that's working.

**Comment by Yawhnie** [comment]
https://github.com/webpack/webpack/issues/4175#issuecomment-323023911

The BEST solution I came across
