### ISSUE TITLE
Need support for redirect Navigation

### ISSUE THREAD

**Issue by nimitjain** [colscott/a-wc-router#19]
If the user wants to redirect to some other route, just to hide the actual route or the default (*) route, there should be a feature for the same

**Comment by colscott** [comment]
The redirect attribute was added. Can be used like this:
```html
        <a-router>
            <a-outlet></a-outlet>
            <a-route path="/page1" element="my-page1"></a-route>
            <a-route path="/page3" redirect="/page1"></a-route>
        </a-router>
```
