### ISSUE TITLE
Default route

### ISSUE THREAD

**Issue by unlight** [colscott/a-wc-router#2]
Hi, I want to set default route for root url.
For example, my current url is `http://localhost:8080/`
And I want to see `entry-list` component in `an-outlet`.
Any of this is not working.
```
    <a-router>
        <an-outlet></an-outlet>
        <a-route path="/" element="entry-list-component" import="entry-list.js"></a-route>
        <a-route path="" element="entry-list-component" import="entry-list.js"></a-route>
        <a-route path="http://localhost:8080/" element="entry-list-component" import="entry-list.js"></a-route>
        <a-route path="http://localhost:8080" element="entry-list-component" import="entry-list.js"></a-route>
        <a-route path="*"><template>Page not found</template></a-route>
    </a-router>
```
Of course, I can do like this:
```
<an-outlet><entry-list-component></entry-list-component></an-outlet>
```
But in this case I must load `entry-list` by app.

So, this behavior by design?

**Comment by colscott** [comment]
Hi @unlight, yes, the idea was that your initial component would go in the an-outlet element.
Is there a reason you don't want to import entry-list in your app? Importing the very first component in your app should improve the first render of the page.

That being said, I don't see why this shouldn't work:
`<a-route path="" element="entry-list-component" import="entry-list.js"></a-route>`

I'll take a look to see why.

**Comment by colscott** [comment]
Try updating to 1.1.3. The following should work now:
`<a-route path="/" element="entry-list-component" import="entry-list.js"></a-route>`

**Comment by unlight** [comment]
> the idea was that your initial component would go in the an-outlet element.
> Is there a reason you don't want to import entry-list in your app?

I thought that is possible initial component may not belong to current application (you know, microfrontends, etc.)

It's working.

But while testing I found a strange behavior:
After notfound page returning to index is not working (notfound stays).
Is it bug?
![a-wc-router-1](https://user-images.githubusercontent.com/301732/59886551-6fd19e80-93d0-11e9-986f-5e642f538fd3.gif)
```
    <nav-component></nav-component>
    <a-router>
        <an-outlet></an-outlet>
        <a-route path="/" element="entry-list-component" lazyload="true" import="./entry-list.js"></a-route>
        <a-route path="*"><template>Page not found</template></a-route>
    </a-router>
```

**Comment by colscott** [comment]
Yeah, that was a bug. Try 1.1.4.

**Comment by fehmi** [comment]
The path="/" is working in main routes but not in nested routes. Is there way to make it work same way with the main routes for nested routes?

**Comment by colscott** [comment]
Hi @fehmi , I'll have to look into that. Could you create a separate issue as this is closed?
In the mean time try adding a redirect to a catch all route with a redirect instead of a path="/" until this is looked into:
```html
    <a-router>
        <an-outlet></an-outlet>
        <a-route path="/route-a" ...></a-route>
        <a-route path="/route-b" ...></a-route>
        <a-route path="*" redirect="/route-a"></a-route>
    </a-router>
```
'/' should then redirect to '/route-a', but so will all other non-matches too.
