### ISSUE TITLE
Add a CDN link [enhancement]

### ISSUE THREAD

**Issue by therealadityashankar** [colscott/a-wc-router#4]
It'd be really cool if I could use this without having to install it via npm, (like as a complete package in itself), a really good use of this would be with [deno](https://deno.land/), or solely as an esmodule

**Comment by therealadityashankar** [comment]
you can use [jsdelivr](https://www.jsdelivr.com/) to do this easily

**Comment by colscott** [comment]
Hi. Thank you for your contribution.
 
Do you mean like this?
https://unpkg.com/browse/a-wc-router@1.1.6/build/esm-bundled/src/router.js

I also try to keep things buildless during my normal work and use es-module-shims a lot:
https://www.npmjs.com/package/es-module-shims
Then you should be able to use the non-build version if that's what you happen to be into:
https://unpkg.com/browse/a-wc-router@1.1.6/src/router.js

I forget the differences between unpkg and jsdelivr. From when I last looked into it (a few years ago though) jsdelivr required a minimum number of GitHub stars or something.

**Comment by therealadityashankar** [comment]
jsdelivr does not (atleast now) require any minimum number of likes

**Comment by therealadityashankar** [comment]
you should add this to the README to help other people too !

**Comment by colscott** [comment]
Looks like it on jsDelivr too now (I never added it, it must have automatically picked up the package like unpkg does).
https://cdn.jsdelivr.net/npm/a-wc-router@1.1.6/src/router.js

I'm sure in the past you had to submit your packages to jsDelivr. Either my memory is bad, or they now automatically pick up npm packages like unpkg does.

**Comment by colscott** [comment]
Added examples to README
